version: '3.8'

services:
  nuxt:
    image: node:15.8.0
    tty: true
    volumes:
      - ./nuxt:/app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    command: npm run dev
    #command: npm run generate
